name: Sync to Gitee

on:
  push:
    branches: ['**']
    tags: ['**']
  delete:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:StarsMilky/AndroidStudioMCPServer.git
          destination-repo: git@gitee.com:star_star_s/android-studio-mcpserver.git
